import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Ticket App",
  description: "Generated by Sohan Prabhath",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow bg-page text-default-text overflow-y-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
